/**
 * Humdrum (**kern and **mxhm) Parser for OMR outputs.
 *
 * Converts Humdrum text generated by JAZZMUS SMT model into structured ScoreDocument.
 * Adheres strictly to the ScoreDocument contracts in src/types/score.ts.
 */

import type {
  HarmonyEvent,
  MelodyEvent,
  NavigationMark,
  PitchStep,
  RationalDuration,
  ScoreDocument,
  ScoreIssue,
  ScoreKeySignature,
  ScoreMeasure,
  ScoreTimeSignature,
  SpelledPitch,
  TempoEvent,
} from "../../types/score.ts";
import { addRational, rational, RATIONAL_ZERO } from "./rational.ts";
import { validateScoreDocument } from "./validation.ts";

export interface HumdrumParseOptions {
  title?: string;
  sourceAssetId?: string;
  persistence?: "ephemeral" | "opted_in";
}

/** Convert a Humdrum **mxhm token (e.g. "C:maj", "A:min7/E") to standard chord symbol. */
export function mxhmToChordSymbol(mxhm: string): string | null {
  const trimmed = mxhm.trim();
  if (!trimmed || trimmed === "." || trimmed === "*" || trimmed === "*-") {
    return null;
  }

  // Handle slash bass
  let chordPart = trimmed;
  let bassPart = "";
  if (trimmed.includes("/")) {
    const parts = trimmed.split("/");
    chordPart = parts[0];
    bassPart = parts[1] || "";
  }

  let root = chordPart;
  let quality = "";

  if (chordPart.includes(":")) {
    const parts = chordPart.split(":");
    root = parts[0];
    quality = parts[1] || "";
  }

  // Normalize root accidentals: Humdrum uses "-" for flat, "#" for sharp
  root = root.replace(/-/g, "b");
  if (bassPart) {
    bassPart = bassPart.replace(/-/g, "b");
  }

  // Map Humdrum quality extensions to standard lead sheet quality
  let standardQuality = "";
  if (quality === "maj" || quality === "none" || !quality) {
    standardQuality = "";
  } else if (quality === "min") {
    standardQuality = "m";
  } else if (quality === "min7") {
    standardQuality = "m7";
  } else if (quality === "maj7") {
    standardQuality = "maj7";
  } else if (quality === "7") {
    standardQuality = "7";
  } else if (quality === "dim") {
    standardQuality = "dim";
  } else if (quality === "dim7") {
    standardQuality = "dim7";
  } else if (quality === "hdim7") {
    standardQuality = "m7b5";
  } else if (quality === "aug") {
    standardQuality = "aug";
  } else if (quality === "aug7") {
    standardQuality = "aug7";
  } else if (quality === "sus4") {
    standardQuality = "sus4";
  } else if (quality === "maj6" || quality === "6") {
    standardQuality = "6";
  } else if (quality === "min6") {
    standardQuality = "m6";
  } else if (quality === "minmaj7") {
    standardQuality = "m(maj7)";
  } else if (quality === "9") {
    standardQuality = "9";
  } else if (quality === "maj9") {
    standardQuality = "maj9";
  } else if (quality === "min9") {
    standardQuality = "m9";
  } else if (quality === "11") {
    standardQuality = "11";
  } else if (quality === "min11") {
    standardQuality = "m11";
  } else if (quality === "13") {
    standardQuality = "13";
  } else {
    // Preserve custom or paren-enclosed extensions
    standardQuality = quality.replace(/min/g, "m").replace(/-/g, "b");
  }

  const baseSymbol = `${root}${standardQuality}`;
  return bassPart ? `${baseSymbol}/${bassPart}` : baseSymbol;
}

/** Parse a Humdrum Kern reciprocal duration into RationalDuration (in quarter-note beats). */
export function parseKernDuration(token: string): RationalDuration {
  const match = token.match(/\d+/);
  if (!match) {
    // Default to quarter note if no duration number is specified
    return rational(1, 1);
  }

  const n = parseInt(match[0], 10);
  if (n <= 0) return rational(1, 1);

  // In Humdrum, n is reciprocal of whole note. Whole note = 4 beats.
  // Base duration in beats = 4 / n
  let dur = rational(4, n);

  // Count dots
  const dotCount = (token.match(/\./g) || []).length;
  if (dotCount === 1) {
    dur = rational(dur.numerator * 3, dur.denominator * 2);
  } else if (dotCount >= 2) {
    dur = rational(dur.numerator * 7, dur.denominator * 4);
  }

  return dur;
}

/** Parse pitch step, accidental alter, and scientific octave from a Kern token. */
export function parseKernPitch(token: string): SpelledPitch | undefined {
  if (token.includes("r")) return undefined; // Rest

  // Match pitch letter
  const letterMatch = token.match(/[a-gA-G]/);
  if (!letterMatch) return undefined;

  const letter = letterMatch[0];
  const step = letter.toUpperCase() as PitchStep;

  // Count occurrences of letter to determine octave
  const letterCount = (token.match(new RegExp(letter, "g")) || []).length;
  let octave = 4;
  if (letter === letter.toLowerCase()) {
    // Lowercase: c=4, cc=5, ccc=6, etc.
    octave = 3 + letterCount;
  } else {
    // Uppercase: C=3, CC=2, CCC=1, etc.
    octave = 4 - letterCount;
  }

  // Alteration
  let alter = 0;
  if (token.includes("##")) alter = 2;
  else if (token.includes("#")) alter = 1;
  else if (token.includes("--")) alter = -2;
  else if (token.includes("-")) alter = -1;
  else if (token.includes("n")) alter = 0;

  return { step, alter, octave };
}

/** Parse key signature interpretation token (e.g. "*k[f#c#]", "*k[b-e-a-]"). */
export function parseKernKey(
  token: string,
  currentMode?: "major" | "minor",
): ScoreKeySignature | undefined {
  if (!token.startsWith("*k[")) return undefined;
  const content = token.slice(3, -1);
  if (content === "") {
    return { fifths: 0, mode: currentMode || "major" };
  }

  const sharps = (content.match(/#/g) || []).length;
  const flats = (content.match(/-/g) || []).length;

  const fifths = sharps > 0 ? sharps : -flats;
  return { fifths, mode: currentMode || "major" };
}

/** Parse time signature interpretation token (e.g. "*M4/4", "*M3/4", "*met(c)"). */
export function parseKernMeter(token: string): ScoreTimeSignature | undefined {
  if (token.startsWith("*M")) {
    const parts = token.slice(2).split("/");
    if (parts.length === 2) {
      const beats = parseInt(parts[0], 10);
      const beatType = parseInt(parts[1], 10);
      if (beats > 0 && beatType > 0) {
        return { beats, beatType };
      }
    }
  } else if (token === "*met(c)") {
    return { beats: 4, beatType: 4 };
  } else if (token === "*met(c|)") {
    return { beats: 2, beatType: 2 };
  }
  return undefined;
}

/** Parse tempo interpretation token (e.g. "*MM120"). */
export function parseKernTempo(token: string): number | undefined {
  if (token.startsWith("*MM")) {
    const bpm = parseInt(token.slice(3), 10);
    if (bpm > 0) return bpm;
  }
  return undefined;
}

/**
 * Parse Humdrum text containing **kern and optional **mxhm spines into a ScoreDocument.
 */
export function parseHumdrumScore(
  humdrumText: string,
  options: HumdrumParseOptions = {},
): ScoreDocument {
  const lines = humdrumText.split(/\r?\n/);
  const measures: ScoreMeasure[] = [];
  const tempoMap: TempoEvent[] = [];
  const issues: ScoreIssue[] = [];

  let currentTime: ScoreTimeSignature = { beats: 4, beatType: 4 };
  let currentKey: ScoreKeySignature = { fifths: 0, mode: "major" };
  let currentTempo = 120;

  let currentMeasureIndex = 0;
  let activeMeasure: ScoreMeasure = {
    id: `m${currentMeasureIndex + 1}`,
    writtenIndex: currentMeasureIndex,
    time: { ...currentTime },
    key: { ...currentKey },
    melody: [],
    harmonies: [],
    navigation: [],
  };

  let currentOffset: RationalDuration = RATIONAL_ZERO;
  let eventCounter = 1;
  let hasActiveEvents = false;

  function closeActiveMeasure(navigationMarks: NavigationMark[] = []): void {
    if (hasActiveEvents || activeMeasure.melody.length > 0 || activeMeasure.harmonies.length > 0) {
      activeMeasure.navigation.push(...navigationMarks);
      measures.push(activeMeasure);
      currentMeasureIndex++;
      currentOffset = RATIONAL_ZERO;
      hasActiveEvents = false;

      activeMeasure = {
        id: `m${currentMeasureIndex + 1}`,
        writtenIndex: currentMeasureIndex,
        time: { ...currentTime },
        key: { ...currentKey },
        melody: [],
        harmonies: [],
        navigation: [],
      };
    } else if (navigationMarks.length > 0) {
      activeMeasure.navigation.push(...navigationMarks);
    }
  }

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    // Ignore spine terminators or linebreaks
    if (trimmed.startsWith("*-") || trimmed === "!!linebreak" || trimmed.startsWith("!")) {
      continue;
    }

    // Split columns by tab
    const cols = trimmed.split("\t");
    const kernCol = cols[0]?.trim() || "";
    const mxhmCol = cols[1]?.trim() || "";

    // 1. Check Barline
    if (kernCol.startsWith("=")) {
      const nav: NavigationMark[] = [];
      let printedNumber: number | undefined;

      const numMatch = kernCol.match(/=(\d+)/);
      if (numMatch) {
        printedNumber = parseInt(numMatch[1], 10);
      }

      if (kernCol.includes("!|:")) {
        nav.push({ kind: "repeat-start" });
      } else if (kernCol.includes(":|!")) {
        nav.push({ kind: "repeat-end" });
      }

      closeActiveMeasure(nav);
      if (printedNumber !== undefined) {
        activeMeasure.printedNumber = printedNumber;
      }
      continue;
    }

    // 2. Check Interpretations
    if (kernCol.startsWith("*")) {
      // Key signature
      const parsedKey = parseKernKey(kernCol, currentKey.mode);
      if (parsedKey) {
        currentKey = parsedKey;
        activeMeasure.key = { ...currentKey };
      }

      // Mode / key tonic (e.g. *c:, *C:)
      const modeMatch = kernCol.match(/^\*([a-gA-G][b#\-]?):$/);
      if (modeMatch) {
        const tonic = modeMatch[1];
        const isMinor = tonic === tonic.toLowerCase();
        currentKey = { ...currentKey, mode: isMinor ? "minor" : "major" };
        activeMeasure.key = { ...currentKey };
      }

      // Time signature
      const parsedMeter = parseKernMeter(kernCol);
      if (parsedMeter) {
        currentTime = parsedMeter;
        activeMeasure.time = { ...currentTime };
      }

      // Tempo
      const bpm = parseKernTempo(kernCol);
      if (bpm) {
        currentTempo = bpm;
        tempoMap.push({
          offset: currentOffset,
          bpm,
          source: "explicit",
        });
      }
      continue;
    }

    // 3. Data Record (Notes & Chords)
    if (kernCol && kernCol !== ".") {
      const duration = parseKernDuration(kernCol);
      const isRest = kernCol.includes("r");
      const pitch = parseKernPitch(kernCol);
      const isGrace = kernCol.includes("q") || kernCol.includes("Q");

      let tie: "start" | "continue" | "stop" | undefined;
      if (kernCol.includes("[") && kernCol.includes("]")) tie = "continue";
      else if (kernCol.includes("[")) tie = "start";
      else if (kernCol.includes("]")) tie = "stop";
      else if (kernCol.includes("_")) tie = "continue";

      const melodyEvent: MelodyEvent = {
        id: `${activeMeasure.id}-m${eventCounter++}`,
        offset: currentOffset,
        duration,
        rest: isRest,
        grace: isGrace,
        pitch,
        tie,
        confidence: 0.95,
      };
      activeMeasure.melody.push(melodyEvent);
      hasActiveEvents = true;

      // Handle chord in mxhm column if present
      if (mxhmCol && mxhmCol !== ".") {
        const chordSymbol = mxhmToChordSymbol(mxhmCol);
        if (chordSymbol) {
          const harmonyEvent: HarmonyEvent = {
            id: `${activeMeasure.id}-h${eventCounter++}`,
            offset: currentOffset,
            duration,
            raw: chordSymbol,
            confidence: 0.95,
            provenance: "photo-omr",
          };
          activeMeasure.harmonies.push(harmonyEvent);
        }
      }

      // Advance offset
      currentOffset = addRational(currentOffset, duration);
    } else if (mxhmCol && mxhmCol !== ".") {
      // Standalone chord without a kern note change
      const chordSymbol = mxhmToChordSymbol(mxhmCol);
      if (chordSymbol) {
        const harmonyEvent: HarmonyEvent = {
          id: `${activeMeasure.id}-h${eventCounter++}`,
          offset: currentOffset,
          raw: chordSymbol,
          confidence: 0.95,
          provenance: "photo-omr",
        };
        activeMeasure.harmonies.push(harmonyEvent);
        hasActiveEvents = true;
      }
    }
  }

  // Close final measure if it contains events
  if (hasActiveEvents || activeMeasure.melody.length > 0 || activeMeasure.harmonies.length > 0) {
    measures.push(activeMeasure);
  }

  // If no tempo was parsed, add default tempo
  if (tempoMap.length === 0) {
    tempoMap.push({
      offset: RATIONAL_ZERO,
      bpm: currentTempo,
      source: "default",
    });
  }

  const doc: ScoreDocument = {
    schemaVersion: 1,
    title: options.title || "Scanned Lead Sheet",
    source: {
      kind: "photo",
      assetId: options.sourceAssetId,
      persistence: options.persistence || "ephemeral",
    },
    key: measures[0]?.key || currentKey,
    time: measures[0]?.time || currentTime,
    tempoMap,
    sections: [],
    measures,
    issues,
  };

  // Run validation to flag any measure duration or shape anomalies
  const validation = validateScoreDocument(doc);
  doc.issues.push(...validation.issues);

  return doc;
}
